<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>onex-boot</artifactId>
        <groupId>com.nb6868.onex</groupId>
        <version>5.0.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>ip2region</artifactId>
    <name>ip2region</name>
    <packaging>jar</packaging>
    <description>离线IP地址定位</description>

    <properties>
        <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
        <skipTests>true</skipTests>
        <destDir>${project.build.outputDirectory}/META-INF/resources/</destDir>
        <!-- version -->
        <ip2region.version>3.3.7</ip2region.version>
    </properties>

    <dependencies>
        <!-- ip2region -->
        <dependency>
            <groupId>org.lionsoul</groupId>
            <artifactId>ip2region</artifactId>
            <version>${ip2region.version}</version>
        </dependency>
    </dependencies>

</project>
