### 首页请求,测试接口是否正常工作
GET http://127.0.0.1:18181/api
Accept: application/json

### GET request with parameter
POST http://127.0.0.1:18181/boot-api/cc/app/user/login
Content-Type: application/json

{
  "type": 102,
  "mobile": "13012345678",
  "smsCode": "123456"
}

### GET request with parameter
POST http://127.0.0.1:18181/boot-api/cc/app/customer/productOutSave
Content-Type: application/json
token: 21666299b80a4275a15f4b7dcea42df8

{
  "shopId": 1,
  "productId": "1346684489190993921",
  "buyerContacts": "123",
  "amount": "3d",
  "buyerMobile": "13252421988"
}

#### GET param content
GET http://localhost:18181/api/sys/param/getContentByCodes?codes=SYS_CFG


