<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>onex-boot</artifactId>
        <groupId>com.nb6868.onex</groupId>
        <version>4.6.28</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>file-converter</artifactId>
    <name>file-converter</name>
    <packaging>jar</packaging>
    <description>文件转换器</description>

    <properties>
        <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
        <skipTests>true</skipTests>
        <!-- libs -->
        <jodconverter.version>4.4.9</jodconverter.version>
    </properties>

    <dependencies>
        <!-- common -->
        <dependency>
            <groupId>com.nb6868.onex</groupId>
            <artifactId>common</artifactId>
            <version>${onex.version}</version>
            <scope>provided</scope>
        </dependency>
        <!-- jodconverter https://github.com/jodconverter/jodconverter -->
        <!-- 核心包 -->
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-core</artifactId>
            <version>${jodconverter.version}</version>
        </dependency>
        <!-- 本地支持包 -->
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-local</artifactId>
            <version>${jodconverter.version}</version>
        </dependency>
        <!-- springboot支持，包括自动配置类 -->
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-spring-boot-starter</artifactId>
            <version>${jodconverter.version}</version>
        </dependency>
    </dependencies>

</project>
